"""Phase Z.6 — is the sibling GAP DISTRIBUTION what teaches the merge?

Where the sequence stands. Z.2: training this head on real frames reproduces the merge (3.22 px at an
8 px gap) where ladder frames give 0.31. Z.3: none of four properties of the real distribution --
brightness variation, rings, object count, crowding -- accounts for it. Z.4: burying the ladder's
pairs in four times as much context costs a factor of 2, not the factor of 10 needed, so it is not
about pairs dominating the frame. Z.5: up-weighting close pairs 30x buys 19% at 8 px -- real, and far
short of a fix.

What is left is the NATURE of the pairs, and `_sample_chi_gaps` (simulation.py:499-510) is where their
separations come from:

    cluster_tight_frac    = 0.32           32% of sibling gaps drawn from...
    cluster_tight_gap_px  = (1.0, 6.0)     ...1-6 px, i.e. 0.4-2.5 sigma at sigma_chi = 2.43 px
    cluster_broad_lognorm = (4.007, 0.95)  the other 68%, lognormal with median 55 px

Measured on generated frames (Z.4/Z.5): `<5 px` 0.173, `<10 px` 0.247 -- only 0.074 of gaps land in
5-10 px. Below ~3 px two peaks are genuinely unresolvable and ONE box is the correct answer; above
~20 px the job is trivial. The distribution is concentrated in both of those regimes and nearly empty
in between -- and the 8 px case the deployed model fails on sits in that hole.

TWO ARMS. Anchors: real 3.22, ladder 0.31, deployed head 3.83, same test slice as Z/Z.2/Z.3/Z.4.

  ARM 1 (does the gap distribution CAUSE it?) -- ladder frames whose pair separations are redrawn
  from the real distribution instead of the fixed 4-24 px rungs. Its control is generated by the SAME
  function with separations drawn uniformly from the rungs, so frame count, planting code, box shape,
  intensity and filtering are all identical and the gap distribution is the only variable.
      real gaps ~ 3.2, ladder gaps ~ 0.3  -> CONFIRMED, the gap distribution is the cause.
      both ~ 0.3                          -> refuted; the ladder's pairs teach resolution whatever
                                             their separations, and the difference is elsewhere again.

  ARM 2 (is it FIXABLE from the config?) -- real frames with `cluster_tight_gap_px` widened, which
  moves the tight component INTO the resolvable band without touching anything else:
      (1, 6)   the shipped value, i.e. the Z.2 baseline re-run here
      (4, 12)
      (6, 20)
      merge weakens with widening -> a data-side lever on a knob that ALREADY EXISTS, and the first
      thing in this whole sequence that could go into a real training run unchanged.
      flat -> the gap distribution is not the lever either, whatever arm 1 says about cause.

The realised gap statistics of every training set are measured and printed -- `<5 px`, the 5-10 px
band, and the median -- so the dose is read off the data rather than assumed from the config.

CAVEAT built in: real gaps have a long tail (lognormal median 55 px), and a pair cannot be planted
wider than the frame allows, so arm 1 clamps draws at 100 px and reports the clamped fraction.

GPU, ~50 min. See tmp_diag/run_gapdist.sbatch.
"""
import os, sys, json, random, time

os.environ.setdefault('LADDER_AXIS', 'chi')
os.environ.setdefault('LADDER_ISO', '1')

_REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _REPO not in sys.path:
    sys.path.insert(0, _REPO)

import numpy as np
import torch
import matplotlib; matplotlib.use('Agg')
import matplotlib.pyplot as plt

import simulation as S
from simulation import FastSimulation
import diagnostics.separation_ladder as L
L.N_IMG = 50
from models.dino.matcher import HungarianMatcher
from diagnostics.prominence_probe import build_model_from_ckpt, CKPT_A, CONFIG, OUT
from diagnostics.head_only_probe import eval_boxbased, per_sep, split_frames, SEPS, \
    C_CLASS, C_BBOX, C_GIOU
from diagnostics.real_frame_head_probe import cache, make_ladder_frames, sibling_gap, N_REAL
from diagnostics.pair_focus_probe import train, add_weights

SIGMA = 8.5 / S.SimulationConfig.a_coef
LADDER_INT = 30.0
N_PAIR = 8
GAP_CLAMP = 100.0                      # a pair cannot be planted wider than the frame allows
TIGHT_RANGES = [(1.0, 6.0), (4.0, 12.0), (6.0, 20.0)]
if os.environ.get('HEADPROBE_SMOKE') == '1':
    TIGHT_RANGES = [(1.0, 6.0), (6.0, 20.0)]


def gap_stats(frames):
    g = np.concatenate([sibling_gap(np.asarray(f[1])) for f in frames])
    g = g[np.isfinite(g)]
    if not len(g):
        return dict(lt5=0.0, band=0.0, med=float('nan'), obj=0.0)
    return dict(lt5=float((g < 5).mean()),
                band=float(((g >= 5) & (g < 10)).mean()),     # the resolvable-and-needed band
                med=float(np.median(g)),
                obj=float(np.mean([len(f[1]) for f in frames])))


def plant_gaps(gaps, rng, box_w, box_h):
    """The ladder's planting geometry, but with a PER-PAIR separation instead of one rung value."""
    H, W = S.HEIGHT, S.WIDTH
    n = len(gaps)
    m = float(np.max(gaps)) / 2 + 8
    qs = np.linspace(0.15 * W + m, 0.90 * W - m, n) + rng.uniform(-8, 8, n)
    lo, hi = 0.22 * H + m, 0.78 * H - m
    if hi <= lo:                                   # very wide draws: fall back to a central band
        lo, hi = 0.35 * H, 0.65 * H
    cs = np.linspace(lo, hi, n) + rng.uniform(-6, 6, n)
    out = []
    for q, c, g in zip(qs, cs, gaps):
        for d in (-g / 2, +g / 2):
            out.append([q - box_w / 2, c + d - box_h / 2, q + box_w / 2, c + d + box_h / 2])
    return np.array(out, dtype=np.float32)


def make_gap_frames(dev, source, n_frames):
    """Ladder-style frames; `source` decides only where the pair separations come from."""
    box_w, box_h = SIGMA * S.SimulationConfig.w_coef, SIGMA * S.SimulationConfig.a_coef
    sim = FastSimulation(device=dev)
    sim.sim_config.prob_single_obj = 0.0
    state = {}
    sim.simulate_labels = lambda _s=sim: (
        torch.tensor(state['gt'], dtype=torch.float32, device=_s.device),
        torch.full((len(state['gt']),), LADDER_INT, device=_s.device),
        torch.zeros(len(state['gt']), dtype=torch.bool, device=_s.device))

    frames, n_clamp, n_draw = [], 0, 0
    rng = np.random.RandomState(555)
    for k in range(n_frames):
        _sd = 31000 + k
        random.seed(_sd); torch.manual_seed(_sd); np.random.seed(_sd)
        if source == 'real':
            g = sim._sample_chi_gaps(N_PAIR).detach().cpu().numpy().astype(np.float64)
            n_draw += len(g); n_clamp += int((g > GAP_CLAMP).sum())
            g = np.clip(g, 1.0, GAP_CLAMP)
        else:                                       # the matched control: the ladder's own rungs
            g = rng.choice(SEPS, N_PAIR).astype(np.float64)
        state['gt'] = plant_gaps(g, rng, box_w, box_h)
        try:
            img, bx, mask, isr = sim.simulate_img()
        except Exception:
            continue
        b = bx.detach().cpu().numpy()
        if len(b) == 0:
            continue
        frames.append((img.detach().cpu(), b, isr.detach().cpu().numpy().astype(np.int64)))
    st = gap_stats(frames)
    st['clamped'] = (n_clamp / n_draw) if n_draw else 0.0
    print(f"  [gaps={source}] {len(frames)} frames, {st['obj']:.1f} obj/frame, <5px {st['lt5']:.3f}, "
          f"5-10px {st['band']:.3f}, median {st['med']:.1f}px, clamped {st['clamped']:.3f}",
          flush=True)
    return frames, st


def make_real(dev, n, tight_range):
    sim = FastSimulation(device=dev)
    sim.sim_config.use_peak_clusters = True
    sim.sim_config.cluster_tight_gap_px = tight_range          # the ONE variable in arm 2
    frames, k = [], 0
    while len(frames) < n and k < n * 4:
        _sd = 4242 + k
        random.seed(_sd); torch.manual_seed(_sd); np.random.seed(_sd)
        k += 1
        try:
            img, bx, mask, isr = sim.simulate_img()
        except Exception:
            continue
        b = bx.detach().cpu().numpy()
        if len(b) == 0:
            continue
        frames.append((img.detach().cpu(), b, isr.detach().cpu().numpy().astype(np.int64)))
    st = gap_stats(frames)
    print(f"  [real tight={tight_range}] {len(frames)} frames, {st['obj']:.1f} obj/frame, "
          f"<5px {st['lt5']:.3f}, 5-10px {st['band']:.3f}, median {st['med']:.1f}px", flush=True)
    return frames, st


def main():
    dev = 'cuda' if torch.cuda.is_available() else 'cpu'
    t0 = time.time()
    print(f"device={dev}  tight ranges={TIGHT_RANGES}", flush=True)

    print("\n--- building frames", flush=True)
    lad = make_ladder_frames(dev, iso=True)
    g_real, s_greal = make_gap_frames(dev, 'real', N_REAL)
    g_lad, s_glad = make_gap_frames(dev, 'ladder', N_REAL)
    reals = {tr: make_real(dev, N_REAL, tr) for tr in TIGHT_RANGES}
    print(f"  built in {time.time() - t0:.0f}s", flush=True)

    print("\n--- caching through the frozen trunk", flush=True)
    model, a = build_model_from_ckpt(CONFIG, CKPT_A, dev)
    c_lad = cache(model, a, lad, dev, ladder=True)
    c_greal = cache(model, a, g_real, dev, ladder=False)
    c_glad = cache(model, a, g_lad, dev, ladder=False)
    c_real = {tr: cache(model, a, reals[tr][0], dev, ladder=False) for tr in TIGHT_RANGES}
    del model; torch.cuda.empty_cache()
    _, va, te = split_frames(c_lad)
    print(f"  ladder {len(c_lad)} (val {len(va)} / test {len(te)}); "
          f"gapreal {len(c_greal)}  gapladder {len(c_glad)}", flush=True)

    matcher = HungarianMatcher(cost_class=C_CLASS, cost_bbox=C_BBOX, cost_giou=C_GIOU,
                               focal_alpha=0.25).to(dev)
    a1, a2 = {}, {}
    for tag, c in (('real gaps', c_greal), ('ladder gaps', c_glad)):
        print(f"\n--- ARM 1: {tag}  ({len(c[:N_REAL])} frames)", flush=True)
        head, lr, ep = train(add_weights(c[:N_REAL], 1.0), va, dev, matcher, tag)
        a1[tag] = per_sep(*eval_boxbased(head, te, dev))
    for tr in TIGHT_RANGES:
        print(f"\n--- ARM 2: real frames, cluster_tight_gap_px={tr}", flush=True)
        head, lr, ep = train(add_weights(c_real[tr][:N_REAL], 1.0), va, dev, matcher, str(tr))
        a2[tr] = per_sep(*eval_boxbased(head, te, dev))

    print("\n" + "=" * 100)
    print("  Median |chi-centre error| px on the ladder test slice")
    print("  anchors: real 3.22 (Z.2)   ladder 0.31 (Z)   deployed head 3.83")
    print("\n  ARM 1 — ladder frames, pair separations redrawn (everything else identical)")
    print("  " + f"{'gap source':<16s}{'<5px':>7s}{'5-10px':>8s}{'med':>7s}" +
          "".join(f"{('sep ' + str(s)):>9s}" for s in SEPS))
    for tag, st in (('real gaps', s_greal), ('ladder gaps', s_glad)):
        ps = a1[tag]
        row = "".join((f"{ps[s]['chi']:9.2f}" if s in ps else f"{'-':>9s}") for s in SEPS)
        print(f"  {tag:<16s}{st['lt5']:7.3f}{st['band']:8.3f}{st['med']:7.1f}{row}")
    print("\n  ARM 2 — real frames, cluster_tight_gap_px widened")
    print("  " + f"{'tight range':<16s}{'<5px':>7s}{'5-10px':>8s}{'med':>7s}" +
          "".join(f"{('sep ' + str(s)):>9s}" for s in SEPS))
    for tr in TIGHT_RANGES:
        ps, st = a2[tr], reals[tr][1]
        row = "".join((f"{ps[s]['chi']:9.2f}" if s in ps else f"{'-':>9s}") for s in SEPS)
        print(f"  {str(tr):<16s}{st['lt5']:7.3f}{st['band']:8.3f}{st['med']:7.1f}{row}")

    json.dump(dict(arm1={k: v for k, v in a1.items()}, arm2={str(k): v for k, v in a2.items()},
                   stats=dict(gap_real=s_greal, gap_ladder=s_glad,
                              real={str(k): v[1] for k, v in reals.items()})),
              open(os.path.join(OUT, 'gap_distribution_probe.json'), 'w'), indent=2, default=str)

    fig, (p1, p2) = plt.subplots(1, 2, figsize=(12, 4.6))
    for tag in a1:
        ss = [s for s in SEPS if s in a1[tag]]
        p1.plot(ss, [a1[tag][s]['chi'] for s in ss], 'o-', label=tag)
    p1.set_title('Arm 1: ladder frames, pair separations redrawn')
    for tr in TIGHT_RANGES:
        ss = [s for s in SEPS if s in a2[tr]]
        p2.plot(ss, [a2[tr][s]['chi'] for s in ss], 's-', label=f'tight gaps {tr}')
    p2.set_title('Arm 2: real frames, cluster_tight_gap_px widened')
    for ax in (p1, p2):
        ax.axhline(3.83, ls=':', c='k', lw=1, label='deployed head')
        ax.axhline(0.31, ls='--', c='g', lw=1, label='ladder-trained')
        ax.set_xscale('log'); ax.set_xticks(SEPS); ax.set_xticklabels(SEPS)
        ax.set_xlabel('planted χ-separation (px)'); ax.set_ylabel('median |χ error| (px)')
        ax.legend(fontsize=7)
    fig.tight_layout()
    p = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'gap_distribution.png')
    fig.savefig(p, dpi=110, bbox_inches='tight')
    print(f"\nsaved {p}\nPROBE DONE  ({time.time() - t0:.0f}s)")


if __name__ == '__main__':
    main()
